Reactable example
dfe-analytical-services/shiny-template pull request #107
Opened 2024-12-12 14:54 UTC by alex-rogers-hub

## Pull request overview

Reactable example beneath datatable example
...

## Pull request checklist

Please check if your PR fulfills the following:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Tests have been run locally and are passing (`shinytest2::test_app()`)
- [ ] Code is styled according to tidyverse styling (checked locally with `styler::style_dir()` and `lintr::lint_dir()`)

## What is the current behaviour?

...

## What is the new behaviour?

...

## Anything else

issue #84 
...

2024-12-18 14:26 UTC, rmbielby requested changes
Couple of small comments to just remove data table. We're just wanting to push a single preferred solution.

Looks like a lot of lintr comments around unnecessary white space. Worth running styler::style_dir() if you haven't already.

2024-12-18 14:26 UTC, rmbielby commented on R/ui_panels/example_tab_1.R
> +                    dataTableOutput("tabBenchmark"),
I think let's just remove the old reference to data table. We're moving towards reactable as we find it easier for to customise.

2024-12-18 14:26 UTC, rmbielby commented on server.R
>    output$tabBenchmark <- renderDataTable({
Again, let's just delete this, the idea is just to replace it with reactable

2024-12-18 15:59 UTC, alex-rogers-hub commented on server.R
>    output$tabBenchmark <- renderDataTable({
on it

2024-12-19 17:04 UTC, rmbielby requested changes
Almost there I think! Just want to get an example of some css styling on the hover/focus etc in there that we can build on when we come to porting this into dfeshiny.

2024-12-19 17:04 UTC, rmbielby commented on server.R
> +      # defaultPageSize and minRows needed for Pagination: example here
Let's avoid the commented out code. Just have it active (with some relatively appropriate values) and analysts can remove it if needed.

I'd also like to have highlight activated similarly to this table here:
https://github.com/dfe-analytical-services/local-authority-interactive-tool/blob/9f7aa4d06969614f55b002b50502a514d3c1d320/R/fn_table_helpers.R#L227

And then let's set an initial styling so we've got a starting point for editing the css as and when we come to that as well, e.g.:

`headerClass = "bar-sort-header",`

2024-12-19 17:04 UTC, rmbielby commented on www/dfe_shiny_gov_style.css
> +
Initial css to back up the change requested in the reactable in server.R

```suggestion
.bar-sort-header:hover,
.bar-sort-header:focus {
  background: #fd0;
}

/* Add a top bar on ascending sort */
.bar-sort-header[aria-sort="ascending"] {
  box-shadow: inset 0 0.188rem 0 0 #1d70b8;
}

/* Add a bottom bar on descending sort */
.bar-sort-header[aria-sort="descending"] {
  box-shadow: inset 0 -0.188rem 0 0 #1d70b8;
}

/* Add an animation when toggling between ascending and descending sort */
.bar-sort-header {
  transition: box-shadow 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}

/* Table row highlighting -------------------------------------------------- */
.rt-tr-highlight:hover {
    background-color: #fd0;
}
```

2025-01-06 17:23 UTC, rmbielby approved these changes

2025-01-08 11:56 UTC, merged