update deployment script to use deployment template defined in dfeshiny
dfe-analytical-services/shiny-template pull request #109
Opened 2024-12-20 16:46 UTC by oadetayo

## Pull request overview
update deploy  template to use reusable template defined in dfeshiny R package

...

2024-12-30 11:44 UTC, cjrace requested changes
This is a really neat solution! I think best to wait until https://github.com/dfe-analytical-services/dfeshiny/pull/74/files is merged in, then finish this PR off. Once it's all in we can then do some testing to make sure it's all working as expected

@rmbielby will definitely be interested in having a look through too when he's back on Thursday

2024-12-30 11:44 UTC, cjrace commented on .github/workflows/deploy-shiny.yaml
> +    uses: dfe-analytical-services/dfeshiny/.github/workflows/dashboard_deploy_template.yaml@17-Deployment-yaml-template
Should we change this to main so that once https://github.com/dfe-analytical-services/dfeshiny/pull/74 is merged it will always pull from the main branch?

```suggestion
    uses: dfe-analytical-services/dfeshiny/.github/workflows/dashboard_deploy_template.yaml@main
```

2024-12-30 11:44 UTC, cjrace commented on parameters.yaml
> +install_gdal: true
Left a comment about updating the name of install_gdal, and adding another argument for installing units dependencies here on your other PR so this will need updating to match what you do in https://github.com/dfe-analytical-services/dfeshiny/pull/74

2025-01-20 12:49 UTC, rmbielby approved these changes

2025-01-20 15:05 UTC, cjrace approved these changes

2025-01-20 15:18 UTC, merged