Added pre-commit hook script to help teams avoid control their data
dfe-analytical-services/shiny-template pull request #19
Opened 2022-07-15 11:15 UTC by rmbielby

We need a method to prevent unpublished data being published to Team's github repositories. We've put together a pre-commit hook such that any files that might be expected to contain some form of data are required to be recorded in a log file. For each file, the logfile requires the full path to that file and a flag listing whether the file contains unpublished, published or reference data. 

Prior to allowing any commit, the pre-commit hook searches for any .csv, .xlsx, .dat, .tex or .pdf files. If any of the files it finds are not present in the log file, the commit is aborted. If any of these files are present in the logfile, but are not listed as published or reference, then the commit will also be aborted.

2022-07-21 08:59 UTC, cjrace requested changes
The pre-commit hooks don't seem to be working - have committed files that aren't in the log, as well as made the example file unpublished and committed that?

2022-08-15 15:20 UTC, chfoster approved these changes
Tested last week & couldn't break it - seemed to work as it should!

2022-08-18 14:16 UTC, cjrace requested changes
Had a look, all working well though only seems to work on R 4.2 or greater, I was on R 4.1.3 when I tried at first and it wouldn't install all the dependencies properly.

Just the one thing around adding an example file in the gitignore for analysts and then I think it's good to merge

2022-08-18 14:16 UTC, cjrace commented on .gitignore
> +*unpublished*
Does this automatically pick up unpublished files or are we expecting teams to add them here (the pre-commit hook message suggests the latter). If we're expecting analysts to add files can we stick in an example file for them to see here?

2022-08-18 14:28 UTC, chfoster commented on .gitignore
> +*unpublished*
Could add a comment instead to explain?

2022-08-23 12:47 UTC, rmbielby commented on .gitignore
> +*unpublished*
@cjrace Have now added an example file that gets excluded from commits, but allows the commit to go ahead. i.e. it's listed in [datafiles_log.csv](https://github.com/dfe-analytical-services/shiny-template/blob/020cb4a6d2a5ab978a7dae4ca88e420eff4a663a/datafiles_log.csv] as unpublished. 

[some_unpublished_data.csv](https://github.com/dfe-analytical-services/shiny-template/blob/020cb4a6d2a5ab978a7dae4ca88e420eff4a663a/data/some_unpublished_data.csv)

2022-08-23 19:52 UTC, cjrace approved these changes

2022-08-24 08:17 UTC, merged