Restyling
dfe-analytical-services/shiny-template pull request #20
Opened 2022-08-16 15:52 UTC by rmbielby

Overhaul of the styling and the example content.

2022-08-18 14:21 UTC, chfoster commented
second dashboard tab still spells out 'heading level 2' not h2, and should we make it so the 'app contents' link actually works and links to the dashboard pages?

2022-08-18 15:24 UTC, rmbielby commented
> second dashboard tab still spells out 'heading level 2' not h2, and should we make it so the 'app contents' link actually works and links to the dashboard pages?

Thanks, fixed those two bits now.

2022-08-23 20:02 UTC, cjrace requested changes
Fairly big issue with the top banner and footer not scaling with the main content. I had a quick play and there seems to be some joy in moving the `govlayout()` function around, though I've not got it working better yet. Examples of the issue

![image](https://user-images.githubusercontent.com/52536248/186254603-c0495ae0-10ce-431c-b140-f846e99fd1ba.png)

![image](https://user-images.githubusercontent.com/52536248/186254646-127c675b-aed7-470c-8877-00a6590431e0.png)

![image](https://user-images.githubusercontent.com/52536248/186254679-9dbae279-6090-4d08-bd65-737e696e11f8.png)

2022-08-23 20:02 UTC, cjrace commented on ui.R
> +      logo = "images/DfE_logo.png"
Can we make the DfE text be an actual link to the DfE page on gov.uk?

2022-08-24 14:22 UTC, rmbielby commented
> Fairly big issue with the top banner and footer not scaling with the main content. I had a quick play and there seems to be some joy in moving the `govlayout()` function around, though I've not got it working better yet. Examples of the issue
> 
> ![image](https://user-images.githubusercontent.com/52536248/186254603-c0495ae0-10ce-431c-b140-f846e99fd1ba.png)
> 
> ![image](https://user-images.githubusercontent.com/52536248/186254646-127c675b-aed7-470c-8877-00a6590431e0.png)
> 
> ![image](https://user-images.githubusercontent.com/52536248/186254679-9dbae279-6090-4d08-bd65-737e696e11f8.png)

Now fixed by switching the use of fluidPage() and fluidRow() in the dashboard panels to gov_main_layout() and gov_row() respectively. The header still behaves the same way, but the content below it now scales along with it.

2022-08-24 14:24 UTC, rmbielby commented on ui.R
> +        "<a href=", site_overflow, ">Mirror</a>."
Updated to Site 1/Site 2. Links are already tracked just with the basic GA I think, without the need for custom events. I've added a link ID to each, which I think should come up in GAs.

2022-08-24 14:29 UTC, rmbielby commented on ui.R
> +      logo = "images/DfE_logo.png"
Good point. Done now.

2022-08-24 14:37 UTC, merged