Updated cookie authorisation to use standard gov uk style banner
dfe-analytical-services/shiny-template pull request #65
Opened 2023-10-27 14:09 UTC by rmbielby

## Pull request overview

Switching to the shiny gov style cookie banner following the work done on the KS4 dashboard.

![image](https://github.com/dfe-analytical-services/shiny-template/assets/230859/3a0ebae7-4824-4326-b8d3-ce1130174a4f)

## Pull request checklist

Please check if your PR fulfils the following:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Tests have been run locally and are passing (`run_tests_locally()`)
- [ ] Code is styled according to tidyverse styling (checked locally with `tidy_code()`)

2023-11-06 11:08 UTC, cjrace requested changes

2023-11-06 11:18 UTC, rmbielby commented on google-analytics.html
> +  <script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
Ah, that's from one of Jen's commits from a little while back, we must not have added her into the commit hook that resets it.

2023-11-06 11:28 UTC, rmbielby commented on google-analytics.html
> +  <script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
Ah, Jen has been added, but it looks like the wrong credentials. Updated now.

2023-11-07 13:27 UTC, rmbielby commented on google-analytics.html
> +  gtag('config', 'G-XXXXXXXXXX');
Fixed as part of above

2023-11-07 13:29 UTC, rmbielby commented on renv/activate.R
> +  version <- "1.0.2"
Nope, it's definitely 1.0.3 now

2023-11-08 12:13 UTC, cjrace reviewed
Not sure if this was pre-existing but the reset button doesn't seem to let you genuinely reset in all cases?

1.) Start app locally and open in browser -> Accept. Then clicking 'reset' removes the line of explanatory text but still seems to be printing tags in the console?

2.) Start app locally and open in browser -> Reject. Then clicking 'reset' removes the line of explanatory text and prints tags to console fine, but you can keep pressing it and I'm not sure what that does? Should it be more of an on / off toggle? 

Basically, I'm confident the initial bit works but if you do want to change them later it doesn't feel obvious what is happening and if you're actually able to? 

Could do similar to what we have on EES as an example - https://explore-education-statistics.service.gov.uk/cookies?

One other issue, is that the line of text explaining how we use the cookies doesn't appear if you start it up and then click view cookies straightaway (as some users may, to inform their decision on whether to accept or reject?).

I can't see obvious changes causing these, so if they were pre-existing then happy to raise these as separate issues to address in a different PR

2023-11-08 14:23 UTC, rmbielby commented
> Not sure if this was pre-existing but the reset button doesn't seem to let you genuinely reset in all cases?
> 
> 1.) Start app locally and open in browser -> Accept. Then clicking 'reset' removes the line of explanatory text but still seems to be printing tags in the console?
> 
> 2.) Start app locally and open in browser -> Reject. Then clicking 'reset' removes the line of explanatory text and prints tags to console fine, but you can keep pressing it and I'm not sure what that does? Should it be more of an on / off toggle?
> 
> Basically, I'm confident the initial bit works but if you do want to change them later it doesn't feel obvious what is happening and if you're actually able to?
> 
> Could do similar to what we have on EES as an example - https://explore-education-statistics.service.gov.uk/cookies?
> 
> One other issue, is that the line of text explaining how we use the cookies doesn't appear if you start it up and then click view cookies straightaway (as some users may, to inform their decision on whether to accept or reject?).
> 
> I can't see obvious changes causing these, so if they were pre-existing then happy to raise these as separate issues to address in a different PR

I think I might just take the "pre-existing" get out clause you've put on these ones. And at least some of the above now comes under dfeshiny rather than the template, so if you're ok with it being deferred to a separate PR, then I think that's my preference.

2023-11-08 15:05 UTC, cjrace commented
No problem, let's do that and get this merged in

2023-11-08 15:06 UTC, cjrace approved these changes

2023-11-08 15:47 UTC, merged