Add dfeshiny package
dfe-analytical-services/shiny-template pull request #66
Opened 2023-10-27 14:13 UTC by rmbielby

## Pull request overview

The dfeshiny package only has functions to run tidy_code() and support_panel() so far, but I've wired these up to keep momentum. This version of the template allows the user to run the dfeshiny version of tidy code (with the local code having been removed) and renders the support panel using the dfeshiny function.

Aiming to add the updated commit hooks in as well from the KS4 dashboard, which would complement this as that uses tidy_code().

## Pull request checklist

Please check if your PR fulfils the following:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Tests have been run locally and are passing (`run_tests_locally()`)
- [ ] Code is styled according to tidyverse styling (checked locally with `tidy_code()`)

2023-11-02 12:34 UTC, cjrace requested changes

2023-11-02 12:34 UTC, cjrace commented on .Rprofile
> -run_tests_locally <- function() {
Why did you remove this function?

2023-11-02 15:16 UTC, rmbielby commented on .Rprofile
> -run_tests_locally <- function() {
Good question... took it out when playing around with the dfeshiny package and should have restored it. Have added it back in now.

2023-11-02 15:16 UTC, rmbielby commented on .Rprofile
> -# Tidy code function
Added.

2023-11-02 17:10 UTC, rmbielby commented on .Rprofile
> -# Tidy code function
Actually that broke the scripts. I've put a prompt to the user to run renv::restore() if dfeshiny isn't available. So now .Rprofile will load it if it is installed and will give a warning if it isn't. And dfeshiny will then get loaded once the user has restored the renv snapshot and then run the app (as dfeshiny is loaded in global.R anyway).

2023-11-06 10:32 UTC, cjrace requested changes
One last small thing before I approve - we seem to get a random line of guidance appear when running the tests? 

![image](https://github.com/dfe-analytical-services/shiny-template/assets/52536248/cbe21938-30f7-48ce-a93e-264cdec5cd02)

2023-11-07 15:33 UTC, cjrace approved these changes

2023-11-07 16:30 UTC, merged