General tidy up
dfe-analytical-services/shiny-template pull request #78
Opened 2024-07-19 07:57 UTC by cjrace

## Pull request overview

Doing a general tidy up of the template ahead of creating a new repo, aiming to resolve some known issues.

## Pull request checklist

Please check if your PR fulfils the following:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Tests have been run locally and are passing (`shinytest2::test_app()`)
- [ ] Code is styled according to tidyverse styling (checked locally with `styler::style_dir()` and `lintr::lint_dir()`)

## Details of changes

...

## Anything else

...

2024-07-22 08:09 UTC, cjrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update shiny template ahead of starting FE dashboard](https://trello.com/c/Vi7YZhrH/1570-update-shiny-template-ahead-of-starting-fe-dashboard)

2024-07-23 10:08 UTC, rmbielby requested changes
Might review this in chunks, here's some initial thoughts from a first sweep...

2024-07-23 10:08 UTC, rmbielby commented on README.md
Could be worth starting a checklist here of things to update when you clone the repo:
- app title in ui.R
- google analytics code
- ...

2024-07-24 10:00 UTC, cjrace commented on R/utils.R
Yeah pretty much, as well as trying to set a standard place to stash custom functions. Though actually, we should keep an eye on https://github.com/dfe-analytical-services/dfeR/pull/71 and stay consistent with the naming there?

2024-07-24 10:17 UTC, cjrace commented on README.md
>  To use this template, click the green "use this template" button at the top of the repo. This will create a copy for you to work off of.
A very good point! Will review when reviewing the readme generally

2024-07-24 10:31 UTC, cjrace commented on README.md
This is partly what I was trying to attempt to resolve, though I think that approach works well - will stop trying to solve the split personality and just split off into a separate thing!

2024-07-24 10:32 UTC, cjrace commented on tests/testthat/test-Server-01-example_dropdown_filtering.R
> +testServer(expr = {
I will definitely have talked about it before, but suspect it's the first time I've actually shown it in action as the only time I've used it in an app was in the map app, will specify the package in the next commit

2024-07-24 10:45 UTC, cjrace commented on R/utils.R
Updated now to `helper_functions.R` as agreed on team tools

2024-07-24 12:32 UTC, cjrace commented on www/dfe_shiny_gov_style.css
Wouldn't describe it as quick, though I've had a play and cleaned up some of the CSS on this - how's that looking now?

2024-08-02 11:08 UTC, cjrace commented on tests/testthat/test-UI-01-basic_load.R
> +})
I started this, and could add something like the following to replace the title UI test:

```
# Test to check if the title has been changed for repositories that aren't the template
# If you have taken the template and not updated the title, this will fail
test_that("Title is no longer the template title", {
  # Capturing the console output to stop messages interrupting the tests
  silence <- capture.output(install.packages("usethis", quiet = TRUE))

  repo_name <- basename(usethis::proj_get())

  if (repo_name != "shiny-template") {
    expect_false(app$get_text("title") ==
      "Department for Education (DfE) Shiny Template - All Local authority maintained schools, England")
  } else {
    expect_true(app$get_text("title") ==
      "Department for Education (DfE) Shiny Template - All Local authority maintained schools, England")
  }
})
```

But I've hesitated as feels slightly complicated for what I'd expect most starting teams to have or be comfortable with maintaining testing wise. I think I'd rather keep a basic title UI test in as simple as possible, and encourage them to understand that and make use of it from the very start as a 'you should always have tests running that check your app loads even during development'. In the readme I'll add that updating the title and this test are always one of the first things to do, what do you think?

An alternative / improvement could be to set the title in the global file or a separate variables script, and then check it always matches that variable. If we did this I think a separate variables script might be nicer to save loading the whole global file each time you run the tests

2024-08-02 11:18 UTC, cjrace commented on README.md
> +...
Removing them now from the main readme

2024-08-02 12:53 UTC, cjrace commented on README.md
Added in the commit where I split the README in two, expect it will grow / update over time

2024-08-02 12:54 UTC, cjrace commented on README.md
>  To use this template, click the green "use this template" button at the top of the repo. This will create a copy for you to work off of.
Updated this in the readme split commit

2024-08-02 12:54 UTC, cjrace commented on README.md
Split off the separate thing now, how does that work?

2024-08-05 11:40 UTC, rmbielby commented on www/dfe_shiny_gov_style.css
Hah, I guess css rarely is! Yeah, looks good now.

2024-08-05 11:44 UTC, rmbielby commented on README.md
Yeah, I think that works a lot better personally.

2024-08-05 11:50 UTC, rmbielby commented on tests/testthat/test-UI-01-basic_load.R
> +})
Yeah, fair. I was feeling similar as I finished the comment above and almost added a line to say "but maybe this is over-complicating things!"

2024-08-05 12:15 UTC, rmbielby requested changes
A few minor suggestions

2024-08-05 12:15 UTC, rmbielby commented on README.md
> +We welcome all suggestions and contributions to this template, and recommend raising an issue in GitHub to start discussions around potential additions or changes with the maintaining team.
Add link around "issue in GitHub" to the template Issues board?

2024-08-05 12:15 UTC, rmbielby commented on README.md
> +We welcome all suggestions and contributions to this template, and recommend raising an issue in GitHub to start discussions around potential additions or changes with the maintaining team.
Could maybe do with other references to the Issues board as well or maybe that's overkill.

2024-08-05 12:15 UTC, rmbielby commented on README_template.md
> +- R at an intermediate level, [DfE R leanring resources](https://dfe-analytical-services.github.io/analysts-guide/learning-development/r.html)
Still got the "leanring" typo in this one. Think I remember seeing that you'd fixed it in the actual readme.

2024-08-05 12:15 UTC, rmbielby commented on README.md
Maybe worth adding an extra note there that certain packages have poor forwards / backwards compatibility between R versions (i.e. older versions of some packages may not install successfully on subsequent versions of R if you've upgraded R locally). Common packages where this is seen are MASS and Matrix. To solve this issue, you can try recording the latest versions of these packages individually in the lockfile: `renv::record("MASS@7.3-61")` and replacing the package version (`7.3-61` in this case) with the latest available version on CRAN (e.g. [MASS](https://cran.r-project.org/web/packages/MASS/index.html) and [Matrix](https://cran.r-project.org/web/packages/Matrix/index.html)).

2024-08-06 11:25 UTC, cjrace commented on README.md
> +GitHub Actions provide CI by running the automated tests and checks for code styling on every pull request into the main branch. The yaml files for these workflows can be found in the .github/workflo
Fixed in 'updating README.md on PR comments' commit

2024-08-06 11:25 UTC, cjrace commented on README.md
> +We welcome all suggestions and contributions to this template, and recommend raising an issue in GitHub to start discussions around potential additions or changes with the maintaining team.
Fixed in 'updating README.md on PR comments' commit

2024-08-06 11:25 UTC, cjrace commented on README_template.md
> +- R at an intermediate level, [DfE R leanring resources](https://dfe-analytical-services.github.io/analysts-guide/learning-development/r.html)
Fixed in 'updating README.md on PR comments' commit

2024-08-06 11:25 UTC, cjrace commented on README.md
Fixed in 'updating README.md on PR comments' commit

2024-08-06 14:33 UTC, rmbielby approved these changes

2024-08-06 16:37 UTC, merged